[package]
name = "rs_syslog_viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
tokio-util = "0.7.17"
notify = "8.1.0"
anyhow = "1.0.100"
chrono = "0.4.43"
lazy_static = "1.5.0"
enum_dispatch = "0.3.13"
